#!/usr/bin/env bash
#configure nginx server to listen for port 80
#this is spam
#this is spam

rm /etc/nginx/sites-enabled/default
#Configure Ngnix to listen to port 80

ln -s /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default

#Restart Nginx
service nginx restart
